# Generated by Django 3.0.8 on 2020-07-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('codigo1', models.CharField(max_length=10)),
                ('codigo2', models.CharField(max_length=10)),
            ],
        ),
    ]
