# Generated by Django 3.0.8 on 2020-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
