# Generated by Django 3.0.8 on 2020-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200727_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='apelido',
            field=models.CharField(default='empresa', max_length=5),
        ),
    ]
