# Generated by Django 3.0.8 on 2020-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200727_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='apelido',
            field=models.CharField(default='empresa', max_length=15),
        ),
    ]
