# Generated by Django 3.0.8 on 2020-07-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200727_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('idempresa', models.CharField(max_length=10)),
                ('carteira', models.IntegerField(default=0)),
                ('minuta', models.IntegerField(default=0)),
                ('faturamento', models.IntegerField(default=0)),
            ],
        ),
    ]
