# Generated by Django 3.0.8 on 2020-07-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200727_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='data',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
