# Generated by Django 3.0.8 on 2020-07-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200730_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='data',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
