# Generated by Django 3.0.8 on 2020-08-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200731_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.CharField(max_length=10)),
                ('codpedido', models.CharField(blank=True, max_length=10, null=True)),
                ('produto', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=20)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('data_faturada', models.DateTimeField()),
                ('datat_devolucao', models.DateTimeField()),
                ('tipo', models.CharField(blank=True, max_length=25, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('representante', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo_devolucao', models.IntegerField(default=0)),
                ('origem_erro', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
