# Generated by Django 3.0.8 on 2020-08-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200810_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='valor',
            field=models.FloatField(),
        ),
    ]
