# Generated by Django 3.0.8 on 2020-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200810_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaPrdocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo1', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo2', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
