# Generated by Django 3.0.8 on 2020-08-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_linhaprdocao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinhaPrdocao',
            new_name='LinhaProdocao',
        ),
    ]
