# Generated by Django 3.0.8 on 2020-08-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20200810_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinhaProdocao',
            new_name='LinhaProducao',
        ),
    ]
