# Generated by Django 3.0.8 on 2020-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_prazoentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoSetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('produto', models.CharField(max_length=100)),
                ('quantidade', models.FloatField()),
                ('peso', models.FloatField()),
                ('cod_setor', models.CharField(blank=True, max_length=4, null=True)),
                ('maquina', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_processo', models.CharField(blank=True, max_length=5, null=True)),
                ('controlado', models.BooleanField(default=True)),
            ],
        ),
    ]
