# Generated by Django 3.0.8 on 2020-08-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200827_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_reprogramacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmotivo', models.IntegerField(default=0)),
                ('descricao', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='reprogramacao',
            name='idmotivo',
            field=models.IntegerField(default=0),
        ),
    ]
