# Generated by Django 3.1.1 on 2020-09-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20200827_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto_Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('descricao', models.CharField(default='', max_length=200)),
                ('idsetor', models.CharField(max_length=4)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('produto', models.CharField(default='', max_length=100)),
                ('quantidade', models.FloatField()),
                ('peso', models.FloatField()),
                ('valor', models.FloatField()),
                ('observacao', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubSetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('nome', models.CharField(default='', max_length=200)),
                ('idsetor', models.CharField(max_length=4)),
            ],
        ),
    ]
