# Generated by Django 3.1.1 on 2020-09-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_ponto_controle_subsetor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_controle',
            name='codigo',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='subsetor',
            name='codigo',
            field=models.CharField(max_length=4),
        ),
    ]
