# Generated by Django 3.1.1 on 2020-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20200913_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto_Controle_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('produto', models.CharField(default='', max_length=100)),
                ('quantidade', models.FloatField()),
                ('peso', models.FloatField()),
                ('valor', models.FloatField()),
                ('observacao', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='ponto_controle',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='ponto_controle',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='ponto_controle',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='ponto_controle',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='ponto_controle',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='ponto_controle',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='ponto_controle',
            name='valor',
        ),
    ]
