# Generated by Django 3.1.1 on 2020-09-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20200913_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Operador',
        ),
    ]
