# Generated by Django 3.1.1 on 2020-09-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20200914_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='idcodigo',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
