# Generated by Django 3.1.1 on 2020-09-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20200914_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='tempo_medio',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
