# Generated by Django 3.1.1 on 2020-09-17 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_processo_tempo_medio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto_controle_evento',
            old_name='codigo',
            new_name='codigo_pc',
        ),
        migrations.RenameField(
            model_name='ponto_controle_evento',
            old_name='fim',
            new_name='data1',
        ),
        migrations.RenameField(
            model_name='ponto_controle_evento',
            old_name='inicio',
            new_name='data2',
        ),
        migrations.RenameField(
            model_name='ponto_controle_evento',
            old_name='observacao',
            new_name='observacao1',
        ),
        migrations.RenameField(
            model_name='ponto_controle_evento',
            old_name='peso',
            new_name='peso1',
        ),
        migrations.RenameField(
            model_name='ponto_controle_evento',
            old_name='quantidade',
            new_name='peso2',
        ),
        migrations.RenameField(
            model_name='ponto_controle_evento',
            old_name='valor',
            new_name='peso3',
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='data3',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='observacao2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='observacao3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='quantidade1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='quantidade2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='quantidade3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='valor1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='valor2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto_controle_evento',
            name='valor3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
