# Generated by Django 3.1.1 on 2020-09-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_auto_20200917_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data1',
            field=models.DateField(default='1976-10-25'),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data2',
            field=models.DateField(default='1976-10-25'),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data3',
            field=models.DateField(default='1976-10-25'),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='observacao1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='observacao2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='observacao3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='peso1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='peso2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='peso3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='quantidade1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='quantidade2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='quantidade3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='valor1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='valor2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='valor3',
            field=models.FloatField(default=0),
        ),
    ]
