# Generated by Django 3.1.1 on 2020-09-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20200917_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data1',
            field=models.DateTimeField(default='1976-10-25 00:00:00'),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data2',
            field=models.DateTimeField(default='1976-10-25 00:00:00'),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data3',
            field=models.DateTimeField(default='1976-10-25 00:00:00'),
        ),
    ]
