# Generated by Django 3.1.1 on 2020-09-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_auto_20200917_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='data3',
            field=models.DateTimeField(null=True),
        ),
    ]
