# Generated by Django 3.1.1 on 2020-09-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_auto_20200917_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='observacao1',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='observacao2',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='observacao3',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
