# Generated by Django 3.1.1 on 2020-09-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_auto_20200917_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='peso1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='peso2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='peso3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='quantidade1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='quantidade2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='quantidade3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='valor1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='valor2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponto_controle_evento',
            name='valor3',
            field=models.FloatField(default=0, null=True),
        ),
    ]
