# Generated by Django 3.1.1 on 2020-09-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_auto_20200917_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_controle',
            name='campos',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
