# Generated by Django 3.1.1 on 2020-09-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_ponto_controle_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='POP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=4)),
                ('codsetor', models.CharField(default='', max_length=4)),
                ('codsubsetor', models.CharField(default='', max_length=4)),
                ('revisao', models.IntegerField(default=0)),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('responsavel', models.CharField(default='', max_length=250)),
                ('revisor', models.CharField(default='', max_length=250)),
                ('tarefa', models.CharField(default='', max_length=500)),
                ('resultado', models.CharField(default='', max_length=500)),
                ('equipamentos', models.CharField(default='', max_length=1000)),
                ('epi', models.CharField(default='', max_length=1000)),
                ('epc', models.CharField(default='', max_length=1000)),
                ('recomendacao', models.CharField(default='', max_length=1000)),
                ('observacao', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=4)),
                ('codigo_tarefa', models.CharField(default='', max_length=4)),
                ('descricao', models.CharField(default='', max_length=1000)),
                ('observacao', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=4)),
                ('codigo_pop', models.CharField(default='', max_length=4)),
                ('descricao', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
