# Generated by Django 3.1.1 on 2020-09-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_pop_procedimento_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo2',
            field=models.CharField(default='', max_length=10),
        ),
    ]
