# Generated by Django 3.1.1 on 2020-09-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_auto_20200918_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=25),
            preserve_default=False,
        ),
    ]
