# Generated by Django 3.1.1 on 2020-09-27 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='motivo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pop',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
